-- ==========================================================
-- RETAILIQ ANALYTICS PLATFORM
-- DAY 15 - BUSINESS ANALYTICS
-- ==========================================================

-- ==========================================================
-- SECTION 1 - EXECUTIVE KPIs
-- ==========================================================

-- Total Revenue
SELECT ROUND(SUM(PAYMENT_VALUE),2) AS TOTAL_REVENUE
FROM FACT_SALES;

-- Total Orders
SELECT COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS
FROM FACT_SALES;

-- Total Customers
SELECT COUNT(DISTINCT CUSTOMER_KEY) AS TOTAL_CUSTOMERS
FROM FACT_SALES;

-- Average Order Value
SELECT
    ROUND(
        SUM(PAYMENT_VALUE) /
        COUNT(DISTINCT ORDER_ID),
        2
    ) AS AVERAGE_ORDER_VALUE
FROM FACT_SALES;

-- Average Items Per Order
SELECT
    ROUND(
        COUNT(*) * 1.0 /
        COUNT(DISTINCT ORDER_ID),
        2
    ) AS AVG_ITEMS_PER_ORDER
FROM FACT_SALES;

-- Average Revenue Per Customer
SELECT
    ROUND(
        SUM(PAYMENT_VALUE) /
        COUNT(DISTINCT CUSTOMER_KEY),
        2
    ) AS AVG_REVENUE_PER_CUSTOMER
FROM FACT_SALES;

-- ==========================================================
-- SECTION 2 - SALES ANALYSIS
-- ==========================================================

-- Revenue by Month
SELECT
    D.YEAR,
    D.MONTH,
    D.MONTH_NAME,
    ROUND(SUM(F.PAYMENT_VALUE),2) AS TOTAL_REVENUE,
    COUNT(DISTINCT F.ORDER_ID) AS TOTAL_ORDERS
FROM FACT_SALES F
JOIN DIM_DATE D
ON F.DATE_KEY = D.DATE_KEY
GROUP BY
    D.YEAR,
    D.MONTH,
    D.MONTH_NAME
ORDER BY
    D.YEAR,
    D.MONTH;

-- Revenue by State
SELECT
    C.CUSTOMER_STATE,
    ROUND(SUM(F.PAYMENT_VALUE),2) AS TOTAL_REVENUE,
    COUNT(DISTINCT F.ORDER_ID) AS TOTAL_ORDERS
FROM FACT_SALES F
JOIN DIM_CUSTOMERS C
ON F.CUSTOMER_KEY = C.CUSTOMER_KEY
GROUP BY
    C.CUSTOMER_STATE
ORDER BY TOTAL_REVENUE DESC;

-- Revenue by Category
SELECT
    P.PRODUCT_CATEGORY_NAME_ENGLISH,
    ROUND(SUM(F.PAYMENT_VALUE),2) AS TOTAL_REVENUE,
    COUNT(*) AS ITEMS_SOLD
FROM FACT_SALES F
JOIN DIM_PRODUCTS P
ON F.PRODUCT_KEY = P.PRODUCT_KEY
GROUP BY
    P.PRODUCT_CATEGORY_NAME_ENGLISH
ORDER BY TOTAL_REVENUE DESC;

-- Top 10 Products
SELECT
    P.PRODUCT_ID,
    P.PRODUCT_CATEGORY_NAME_ENGLISH,
    ROUND(SUM(F.PAYMENT_VALUE),2) AS TOTAL_REVENUE
FROM FACT_SALES F
JOIN DIM_PRODUCTS P
ON F.PRODUCT_KEY = P.PRODUCT_KEY
GROUP BY
    P.PRODUCT_ID,
    P.PRODUCT_CATEGORY_NAME_ENGLISH
ORDER BY TOTAL_REVENUE DESC
LIMIT 10;

-- Top 10 Sellers
SELECT
    S.SELLER_ID,
    S.SELLER_STATE,
    ROUND(SUM(F.PAYMENT_VALUE),2) AS TOTAL_REVENUE,
    COUNT(DISTINCT F.ORDER_ID) AS TOTAL_ORDERS
FROM FACT_SALES F
JOIN DIM_SELLERS S
ON F.SELLER_KEY = S.SELLER_KEY
GROUP BY
    S.SELLER_ID,
    S.SELLER_STATE
ORDER BY TOTAL_REVENUE DESC
LIMIT 10;

-- ==========================================================
-- SECTION 3 - CUSTOMER ANALYSIS
-- ==========================================================

-- Top Customers
SELECT
    C.CUSTOMER_ID,
    C.CUSTOMER_CITY,
    C.CUSTOMER_STATE,
    ROUND(SUM(F.PAYMENT_VALUE),2) AS TOTAL_REVENUE,
    COUNT(DISTINCT F.ORDER_ID) AS TOTAL_ORDERS
FROM FACT_SALES F
JOIN DIM_CUSTOMERS C
ON F.CUSTOMER_KEY = C.CUSTOMER_KEY
GROUP BY
    C.CUSTOMER_ID,
    C.CUSTOMER_CITY,
    C.CUSTOMER_STATE
ORDER BY TOTAL_REVENUE DESC
LIMIT 10;

-- Customer Order Frequency
SELECT
    C.CUSTOMER_ID,
    COUNT(DISTINCT F.ORDER_ID) AS TOTAL_ORDERS,
    ROUND(SUM(F.PAYMENT_VALUE),2) AS TOTAL_REVENUE
FROM FACT_SALES F
JOIN DIM_CUSTOMERS C
ON F.CUSTOMER_KEY = C.CUSTOMER_KEY
GROUP BY C.CUSTOMER_ID
ORDER BY TOTAL_ORDERS DESC;

-- Average Customer Spend
SELECT
    ROUND(AVG(CUSTOMER_TOTAL_SPEND),2) AS AVG_CUSTOMER_SPEND
FROM
(
    SELECT
        CUSTOMER_KEY,
        SUM(PAYMENT_VALUE) AS CUSTOMER_TOTAL_SPEND
    FROM FACT_SALES
    GROUP BY CUSTOMER_KEY
);

-- Customer Ranking
SELECT
    C.CUSTOMER_ID,
    ROUND(SUM(F.PAYMENT_VALUE),2) AS TOTAL_REVENUE,
    RANK() OVER(ORDER BY SUM(F.PAYMENT_VALUE) DESC) AS CUSTOMER_RANK
FROM FACT_SALES F
JOIN DIM_CUSTOMERS C
ON F.CUSTOMER_KEY = C.CUSTOMER_KEY
GROUP BY C.CUSTOMER_ID;

-- Customer Lifetime Value
SELECT
    C.CUSTOMER_ID,
    COUNT(DISTINCT F.ORDER_ID) AS TOTAL_ORDERS,
    ROUND(SUM(F.PAYMENT_VALUE),2) AS CUSTOMER_LIFETIME_VALUE
FROM FACT_SALES F
JOIN DIM_CUSTOMERS C
ON F.CUSTOMER_KEY = C.CUSTOMER_KEY
GROUP BY C.CUSTOMER_ID
ORDER BY CUSTOMER_LIFETIME_VALUE DESC;

-- ==========================================================
-- SECTION 4 - PRODUCT ANALYSIS
-- ==========================================================

-- Top Products
SELECT
    P.PRODUCT_ID,
    P.PRODUCT_CATEGORY_NAME_ENGLISH,
    ROUND(SUM(F.PAYMENT_VALUE),2) AS TOTAL_REVENUE
FROM FACT_SALES F
JOIN DIM_PRODUCTS P
ON F.PRODUCT_KEY = P.PRODUCT_KEY
GROUP BY
    P.PRODUCT_ID,
    P.PRODUCT_CATEGORY_NAME_ENGLISH
ORDER BY TOTAL_REVENUE DESC
LIMIT 10;

-- Category Revenue
SELECT
    P.PRODUCT_CATEGORY_NAME_ENGLISH,
    ROUND(SUM(F.PAYMENT_VALUE),2) AS TOTAL_REVENUE
FROM FACT_SALES F
JOIN DIM_PRODUCTS P
ON F.PRODUCT_KEY = P.PRODUCT_KEY
GROUP BY P.PRODUCT_CATEGORY_NAME_ENGLISH
ORDER BY TOTAL_REVENUE DESC;

-- Category Ranking
SELECT
    P.PRODUCT_CATEGORY_NAME_ENGLISH,
    ROUND(SUM(F.PAYMENT_VALUE),2) AS TOTAL_REVENUE,
    DENSE_RANK() OVER(ORDER BY SUM(F.PAYMENT_VALUE) DESC) AS CATEGORY_RANK
FROM FACT_SALES F
JOIN DIM_PRODUCTS P
ON F.PRODUCT_KEY = P.PRODUCT_KEY
GROUP BY P.PRODUCT_CATEGORY_NAME_ENGLISH;

-- ==========================================================
-- SECTION 5 - TIME ANALYSIS
-- ==========================================================

-- Monthly Revenue
WITH MONTHLY_REVENUE AS
(
SELECT
    D.YEAR,
    D.MONTH,
    D.MONTH_NAME,
    SUM(F.PAYMENT_VALUE) AS TOTAL_REVENUE
FROM FACT_SALES F
JOIN DIM_DATE D
ON F.DATE_KEY = D.DATE_KEY
GROUP BY
    D.YEAR,
    D.MONTH,
    D.MONTH_NAME
)

SELECT
    *,
    LAG(TOTAL_REVENUE)
        OVER(ORDER BY YEAR,MONTH) AS PREVIOUS_MONTH_REVENUE,
    SUM(TOTAL_REVENUE)
        OVER(ORDER BY YEAR,MONTH) AS RUNNING_TOTAL_REVENUE
FROM MONTHLY_REVENUE;

-- Quarterly Revenue
SELECT
    D.YEAR,
    D.QUARTER,
    ROUND(SUM(F.PAYMENT_VALUE),2) AS TOTAL_REVENUE
FROM FACT_SALES F
JOIN DIM_DATE D
ON F.DATE_KEY = D.DATE_KEY
GROUP BY
    D.YEAR,
    D.QUARTER
ORDER BY
    D.YEAR,
    D.QUARTER;

-- Weekend vs Weekday Sales
SELECT
    D.IS_WEEKEND,
    ROUND(SUM(F.PAYMENT_VALUE),2) AS TOTAL_REVENUE,
    COUNT(DISTINCT F.ORDER_ID) AS TOTAL_ORDERS
FROM FACT_SALES F
JOIN DIM_DATE D
ON F.DATE_KEY = D.DATE_KEY
GROUP BY D.IS_WEEKEND;